### ISSUE TITLE
2019년 5월 서버 Todo Check List

### ISSUE THREAD

**Issue by gaepury** [freshpotatoteam/DocsCare#11]
#### 1. AWS 서버 세팅 및 배포
- beanstalk 도입
   - 학습은 script로 직접 돌려야 해서 서버 내에서 하는 작업이 많을텐데 beanstalk로 하는게 맞을까?..
   - beanstalk은 다음에 써보는걸로..
- [x] 서버 배포
   - swagger url: http://15.164.143.16/swagger-ui
- [x] CloudFront - S3 연동

#### 2. flask api 구현(#10 )
- [x] 이미지 조회 api 
   - 카테고리별 전체 조회 (path or param: user id and category)
      - category_id = 'all'시 전체문서 조회
   - 이미지 단일 조회(path or param: user id and image id)
- [x] 이미지 저장 api(path or param: user id, image id(AI key))
   - Image Document 추가
   - S3 저장
   - User Document category 변경
- [x] 이미지 카테고리 변경 api(path or param: user id, category key or name)
- [x] 이미지 이름 변경 api(path or param: user id, image_name)
- [x] 이미지 text기반 검색 api(path or param: user id, text)
- [x] 이미지 단일 삭제 api
- [x] 카테고리 CRUD api
   - 카테고리 추가
   - 카테고리 삭제
   - 카테고리 이름 변경
   - 카테고리 조회

#### 3. 이미지 ocr 분석 test
- [x] test
- 여러 언어에 대해서 저장할수 있는 방법은?.. 
   - ![image](https://user-images.githubusercontent.com/20143765/58383562-752b0b80-8013-11e9-8211-18ea96b78fd1.png)
   - ``lang="eng+kor+chi_sim"``

#### 4. 이미지 thunbnail 생성 test
- [x] test
- thumbnail 생성 및 s3 folder 분리
   - source, thumbnail

#### 5. API Security
- [x] X-API-KEY Header를 이용한 처리
  -  API 요청시 Header X-API-KEY: c30d6e11-67cc-4643-8e20-b2cdff2799ef) 전달

#### 6. Image bulk 학습 방식 검토
- [ ] #9 training sample Image Bulk 크롤링, category train flow 검토
