### ISSUE TITLE
2019년 4월 서버 Todo Check List

### ISSUE THREAD

**Issue by pennya** [freshpotatoteam/DocsCare#2]
#### 1.  DB 종류 선택 및 스키마 설계
- [x] DB 선택 (mysql?, mongo?, elk(텍스트 기반이니..)?)
   - mongo for simple
- [x] mongodb atlas 등록
- [x] API용 DB Schema 설계(#7)
- [x] flask - mongo db 연동

#### 2. ec2, s3, cloud front, iam 등 생성 (#8)
- [x] ec2
   - t2.small instance 생성(cpu 1core, memory 2g)(2019.04.19)
- [x] s3
   - [x] S3 생성 및 파이썬 연동
- [ ] ec2 서버 설정
   - docker, git 등 설치
   - 이렇게 하지 말고 beanstalk를 사용해보자.

#### 3.  project 구조 세팅
- [x] flask api, modeling(학습) 멀티 모듈 형태로 구성되어야함.
   - 최종 결과(multi module 형태는 아님..)
   - Backend 아래 flaskr(backend_api), model(backend_model) 형태
      - ![image](https://user-images.githubusercontent.com/20143765/56438091-b5b0ae80-631c-11e9-963d-7c583a3d1ac0.png)
         - conf, tests, venv등은 공통
         - requirement.txt: python module 이름 관리
         - settings.py: 설정값 관리 파일
   - Flask Namespace을 이용하여 모듈(파일)별로 route 분리(분리 관리)

#### 4. flask api 구현(#10 )
- [x] 회원 가입, 탈퇴 api
- [ ] 이미지 조회 api 
   - 카테고리별 전체 조회 (path or param: user id and category)
   - 이미지 하나 조회(path or param: user id and image id)
- [ ] 이미지 저장 api(path or param: user id, image id(AI key))
   - DB insert logic
   - ocr를 이용하여 이미지를 텍스트로 변환 후 학습된 모델에 넣어서 바로 카테고리 예측값까지 반환할지?
      - ocr 성능 리서치
      - 모델에 넣어서 예측하는것은 크게 오래 걸리지 않을것.
- [ ] 이미지 카테고리 변경 api(path or param: user id, category key or name)

#### 5. 이미지 ocr 분석 test
- [ ] Test

#### 6. 신경망 종류 생각해보기 (RNN 등..)
- [x] #4 

#### 7. 이미지 thunbnail 생성 test
- [ ] text
