### ISSUE TITLE
2019년 6월 서버 Todo Check List

### ISSUE THREAD

**Issue by gaepury** [freshpotatoteam/DocsCare#22]
#### 1. 카테고리 자동 분류를 위한 작업(category train flow)
- [x] 학습 샘플 이미지 습득
   - [x] bulk 이미지 크롤링 방식 검토
   - google_image_download(구글 이미지 다운로드용) + chromedriver(bulk용) library 이용
       - Limit 100 초과시 이슈
          - https://github.com/hardikvasa/google-images-download/issues/159
          - arguments 수정
          - ![image](https://user-images.githubusercontent.com/20143765/59967153-4431ee00-9561-11e9-9344-5cb1b1c9af85.png)
- [x] 학습 이미지 OCR 처리를 통한 텍스트 변환
   - [x] flaskr/image/service 에서 process_image module 복사
- [x] OCR 데이터 전처리(형태소 분석)
   - [x] 한글, 영어 토크나이저 분리 
      - 한글: konlpy.tag의 Okt.nouns 메서드 사용
      - 영어: nltk.tokenize 메서드 사용
   - [x] text classifcation research
- [x] 전처리 결과 Mongo DB categorySampleData Collection에 저장
   - [x] DB module 불러오기
   - [x] 데이터 수집 및 전처리, 저장 후 이미지 삭제
   - [x] 데이터 저장 구조(category_sample_data_document) 검토
      - [x] Training 데이터 갯수 정하기 및 저장(batch..)
         - 카테고리별(by category_id) 2/3는 학습데이터, 1/3는 테스트데이터
- [x] 학습 샘플 이미지 습득 - OCR 처리를 통한 텍스트화 - 텍스트 데이터 전처리 - 데이터 저장 Flow 소요시간 check
   - 16:05 ~ 15:00 (약 23시간)
- [x] 카테고리 분류 학습기 개발
   -  한글 + 영어 혼합된 모델 vs 분리된 모델
   - |     | 혼합된 모델 | 분리된 모델 |
      |---|---|---|
      | 장점 |간단함 | 성능 좋음 |
      | 단점 | 성능이 안좋음 | 귀찮음 |
  - 최종
      - Only 한글 모델
         - 영어, 빈 tokenizer 결과 필터링해서 학습

#### 2. flask api 구현(#10 )
- 이미지 저장 api 
   - [x] Thumbnail 저장 이슈(제대로 저장 안됨)
   - [x] PDF 파일 처리 
      - [x] PDF 파일 저장 이슈
      - [x] PDF 파일 Thumbnail 생성 이슈
      - [x] PDF 파일 OCR 처리 이슈
         - [x] OCR 처리 향상
            - 한자 제외
            - PDF 2번째 페이지 이미지 까지만 OCR
      - [x] pdg2image library Docker file dependency 추가 및 배포
   - [x] 카테고리 분류 학습기를 이용한 자동 분류 결과 API 적용
      - OCR처리 영어+한글 합침 vs 분리 ..?
         - 합쳤을때:
            - 한글 + 영어 혼합된 모델에만 사용 가능. 
         - 분리했을때: 
            - 어떻게 predict 체크를 해야될까..? 각 언어에 대해서 ocr처리를 두번해 각각 모델(혼합된 모델 or 분리된 모델)에 넣어 predict를 구해야 하고 그중에 가장 높은 predict를 가진 카테고리로 분류? 
                - ㅇㅋ 이방법이 가장 명확해 보임
       - 최종
          - eng+kor 로 ocr 돌리고 결과값으로 한글 타입 toknizer시켜서 most_similar 메서드를 이용해서 가장 유사도 높은 category_id 반환

### 3. 서버 세팅 및 배포
- [x] ocr language data docker file 적용
- [x] tesseract, pdf2image library 및 dependency 설치

#### 3. QA 및 버그 Fix
- #23 [Backend] 버그 및 Q&A
