### ISSUE TITLE
training sample Image Bulk 크롤링, category train flow 검토

### ISSUE THREAD

**Issue by gaepury** [freshpotatoteam/DocsCare#9]
#### Python bulk image download 방법
- https://creativeworks.tistory.com/entry/%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EA%B5%AC%EA%B8%80-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%8D%94-%EB%A7%8C%EB%93%A4%EA%B8%B0-Making-Image-Downloader-from-google-image-by-using-Python
- https://github.com/hardikvasa/google-images-download
- https://stackoverflow.com/questions/20716842/python-download-images-from-google-image-search

#### Task
- [x] Python bulk image download
   - [x] 다양한 검색기반으로 image를 조회해야하는데 효과적으로 할 수 있는 방법 검토
- [x] image to string by OCR
- [x] DB insert(by category)
   - OCR +Tokenizer 결과, category_id(static한 값)
- [x] Training model(분류기) 구현
- [x] Image Post API에 Training Model을 이용한 카테고리 분류 로직 구현
   - classifi_category_by_image_string() function 
- [ ] 지속적인 model 학습 방법 검토
